[package]
name = "ecdsa-methods"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "^3.0.3" }

[build-dependencies]
risc0-build = { version = "^3.0.3" }

[package.metadata.risc0]
methods = ["guest"]
